//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingTable.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingTable.Web.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        public static string Content_AccountNumber {
            get {
                return ResourceManager.GetString("Content_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Content_Action {
            get {
                return ResourceManager.GetString("Content_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Content_Active {
            get {
                return ResourceManager.GetString("Content_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Content_Add {
            get {
                return ResourceManager.GetString("Content_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New or Update.
        /// </summary>
        public static string Content_AddOrUpdate {
            get {
                return ResourceManager.GetString("Content_AddOrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Content_Address {
            get {
                return ResourceManager.GetString("Content_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the terms.
        /// </summary>
        public static string Content_AgreeTerms {
            get {
                return ResourceManager.GetString("Content_AgreeTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Content_All {
            get {
                return ResourceManager.GetString("Content_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day.
        /// </summary>
        public static string Content_Allday {
            get {
                return ResourceManager.GetString("Content_Allday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have a membership.
        /// </summary>
        public static string Content_AlreadyMemeber {
            get {
                return ResourceManager.GetString("Content_AlreadyMemeber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due.
        /// </summary>
        public static string Content_AmountDue {
            get {
                return ResourceManager.GetString("Content_AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any floor.
        /// </summary>
        public static string Content_AnyFloor {
            get {
                return ResourceManager.GetString("Content_AnyFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Content_Available {
            get {
                return ResourceManager.GetString("Content_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Content_Back {
            get {
                return ResourceManager.GetString("Content_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic info.
        /// </summary>
        public static string Content_BasicInfo {
            get {
                return ResourceManager.GetString("Content_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Content_Birthday {
            get {
                return ResourceManager.GetString("Content_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Content_Book {
            get {
                return ResourceManager.GetString("Content_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked.
        /// </summary>
        public static string Content_Booked {
            get {
                return ResourceManager.GetString("Content_Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string Content_Booking {
            get {
                return ResourceManager.GetString("Content_Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking confirm.
        /// </summary>
        public static string Content_BookingConfirm {
            get {
                return ResourceManager.GetString("Content_BookingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking limit.
        /// </summary>
        public static string Content_BookingLimit {
            get {
                return ResourceManager.GetString("Content_BookingLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Table.
        /// </summary>
        public static string Content_BookingTable {
            get {
                return ResourceManager.GetString("Content_BookingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear and Rebook.
        /// </summary>
        public static string Content_ClearAndRebook {
            get {
                return ResourceManager.GetString("Content_ClearAndRebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to clear booking and rebook!.
        /// </summary>
        public static string Content_ClearBooking {
            get {
                return ResourceManager.GetString("Content_ClearBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Content_Close {
            get {
                return ResourceManager.GetString("Content_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company info.
        /// </summary>
        public static string Content_CompanyInfo {
            get {
                return ResourceManager.GetString("Content_CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string Content_CompanyName {
            get {
                return ResourceManager.GetString("Content_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Content_Completed {
            get {
                return ResourceManager.GetString("Content_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content_Content {
            get {
                return ResourceManager.GetString("Content_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation time.
        /// </summary>
        public static string Content_CreationTime {
            get {
                return ResourceManager.GetString("Content_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Content_Creator {
            get {
                return ResourceManager.GetString("Content_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Content_Customer {
            get {
                return ResourceManager.GetString("Content_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer info.
        /// </summary>
        public static string Content_CustomerInfo {
            get {
                return ResourceManager.GetString("Content_CustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Content_Date {
            get {
                return ResourceManager.GetString("Content_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Content_Delete {
            get {
                return ResourceManager.GetString("Content_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string Content_Deposit {
            get {
                return ResourceManager.GetString("Content_Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Content_Description {
            get {
                return ResourceManager.GetString("Content_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Content_Details {
            get {
                return ResourceManager.GetString("Content_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable .
        /// </summary>
        public static string Content_Disable {
            get {
                return ResourceManager.GetString("Content_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Content_Discount {
            get {
                return ResourceManager.GetString("Content_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount and Tax.
        /// </summary>
        public static string Content_DiscountAndTax {
            get {
                return ResourceManager.GetString("Content_DiscountAndTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Content_Edit {
            get {
                return ResourceManager.GetString("Content_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Content_Email {
            get {
                return ResourceManager.GetString("Content_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Content_Enable {
            get {
                return ResourceManager.GetString("Content_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Content_Enter {
            get {
                return ResourceManager.GetString("Content_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Content_Error {
            get {
                return ResourceManager.GetString("Content_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Content_Floor {
            get {
                return ResourceManager.GetString("Content_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Content_Food {
            get {
                return ResourceManager.GetString("Content_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password.
        /// </summary>
        public static string Content_ForgotPassword {
            get {
                return ResourceManager.GetString("Content_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Content_Free {
            get {
                return ResourceManager.GetString("Content_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Content_From {
            get {
                return ResourceManager.GetString("Content_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Content_Fullname {
            get {
                return ResourceManager.GetString("Content_Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Infomation.
        /// </summary>
        public static string Content_GeneralInfomation {
            get {
                return ResourceManager.GetString("Content_GeneralInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have no valid table.
        /// </summary>
        public static string Content_HaveNoValidTable {
            get {
                return ResourceManager.GetString("Content_HaveNoValidTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}! Welcome to {1}..
        /// </summary>
        public static string Content_HelloNewMember {
            get {
                return ResourceManager.GetString("Content_HelloNewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}! Welcome back..
        /// </summary>
        public static string Content_HelloOldMember {
            get {
                return ResourceManager.GetString("Content_HelloOldMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Content_Hi {
            get {
                return ResourceManager.GetString("Content_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Content_Home {
            get {
                return ResourceManager.GetString("Content_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Content_Hour {
            get {
                return ResourceManager.GetString("Content_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Content_Id {
            get {
                return ResourceManager.GetString("Content_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card.
        /// </summary>
        public static string Content_IdentityCard {
            get {
                return ResourceManager.GetString("Content_IdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Content_Image {
            get {
                return ResourceManager.GetString("Content_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Content_Inactive {
            get {
                return ResourceManager.GetString("Content_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Content_Info {
            get {
                return ResourceManager.GetString("Content_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Content_Invoice {
            get {
                return ResourceManager.GetString("Content_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Info.
        /// </summary>
        public static string Content_InvoiceInfo {
            get {
                return ResourceManager.GetString("Content_InvoiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string Content_Live {
            get {
                return ResourceManager.GetString("Content_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Content_Locked {
            get {
                return ResourceManager.GetString("Content_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Content_Login {
            get {
                return ResourceManager.GetString("Content_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or register.
        /// </summary>
        public static string Content_LoginOrRegister {
            get {
                return ResourceManager.GetString("Content_LoginOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Content_Menu {
            get {
                return ResourceManager.GetString("Content_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Content_Mode {
            get {
                return ResourceManager.GetString("Content_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Max size 1024x1024).
        /// </summary>
        public static string Content_MostSuitableSize {
            get {
                return ResourceManager.GetString("Content_MostSuitableSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Content_Name {
            get {
                return ResourceManager.GetString("Content_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Content_New {
            get {
                return ResourceManager.GetString("Content_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new customer.
        /// </summary>
        public static string Content_NewMembership {
            get {
                return ResourceManager.GetString("Content_NewMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Content_NewPassword {
            get {
                return ResourceManager.GetString("Content_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Content_Next {
            get {
                return ResourceManager.GetString("Content_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Deposit when you order food.
        /// </summary>
        public static string Content_NoDeposit {
            get {
                return ResourceManager.GetString("Content_NoDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not required.
        /// </summary>
        public static string Content_NoRequired {
            get {
                return ResourceManager.GetString("Content_NoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Content_Note {
            get {
                return ResourceManager.GetString("Content_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Content_Now {
            get {
                return ResourceManager.GetString("Content_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Content_Number {
            get {
                return ResourceManager.GetString("Content_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Content_Ok {
            get {
                return ResourceManager.GetString("Content_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string Content_OldPassword {
            get {
                return ResourceManager.GetString("Content_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Content_Online {
            get {
                return ResourceManager.GetString("Content_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered.
        /// </summary>
        public static string Content_Ordered {
            get {
                return ResourceManager.GetString("Content_Ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Food.
        /// </summary>
        public static string Content_OrderFood {
            get {
                return ResourceManager.GetString("Content_OrderFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Content_OrderID {
            get {
                return ResourceManager.GetString("Content_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order info.
        /// </summary>
        public static string Content_OrderInfo {
            get {
                return ResourceManager.GetString("Content_OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can order when you come!.
        /// </summary>
        public static string Content_OrderLater {
            get {
                return ResourceManager.GetString("Content_OrderLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Content_Orders {
            get {
                return ResourceManager.GetString("Content_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order time.
        /// </summary>
        public static string Content_OrderTime {
            get {
                return ResourceManager.GetString("Content_OrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Content_Password {
            get {
                return ResourceManager.GetString("Content_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirm .
        /// </summary>
        public static string Content_PasswordConfirm {
            get {
                return ResourceManager.GetString("Content_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Content_Pay {
            get {
                return ResourceManager.GetString("Content_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay and Print.
        /// </summary>
        public static string Content_PayAndPrint {
            get {
                return ResourceManager.GetString("Content_PayAndPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed by.
        /// </summary>
        public static string Content_PayedBy {
            get {
                return ResourceManager.GetString("Content_PayedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payee ID.
        /// </summary>
        public static string Content_PayeeId {
            get {
                return ResourceManager.GetString("Content_PayeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Info.
        /// </summary>
        public static string Content_PaymentInfo {
            get {
                return ResourceManager.GetString("Content_PaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Success.
        /// </summary>
        public static string Content_PaymentSuccess {
            get {
                return ResourceManager.GetString("Content_PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Time.
        /// </summary>
        public static string Content_PaymentTime {
            get {
                return ResourceManager.GetString("Content_PaymentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal.
        /// </summary>
        public static string Content_Paypal {
            get {
                return ResourceManager.GetString("Content_Paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDT Token.
        /// </summary>
        public static string Content_PDTToken {
            get {
                return ResourceManager.GetString("Content_PDTToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Content_Pending {
            get {
                return ResourceManager.GetString("Content_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending orders.
        /// </summary>
        public static string Content_PendingOrders {
            get {
                return ResourceManager.GetString("Content_PendingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Content_Permission {
            get {
                return ResourceManager.GetString("Content_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Content_Phone {
            get {
                return ResourceManager.GetString("Content_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Content_Photo {
            get {
                return ResourceManager.GetString("Content_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Content_Price {
            get {
                return ResourceManager.GetString("Content_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Content_Print {
            get {
                return ResourceManager.GetString("Content_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Content_Profile {
            get {
                return ResourceManager.GetString("Content_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Content_Qty {
            get {
                return ResourceManager.GetString("Content_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Content_Quantity {
            get {
                return ResourceManager.GetString("Content_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Content_Register {
            get {
                return ResourceManager.GetString("Content_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Content_RememberMe {
            get {
                return ResourceManager.GetString("Content_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant info.
        /// </summary>
        public static string Content_RestaurantInfo {
            get {
                return ResourceManager.GetString("Content_RestaurantInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Content_Review {
            get {
                return ResourceManager.GetString("Content_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Content_Role {
            get {
                return ResourceManager.GetString("Content_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Content_Sale {
            get {
                return ResourceManager.GetString("Content_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Content_Save {
            get {
                return ResourceManager.GetString("Content_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Content_Search {
            get {
                return ResourceManager.GetString("Content_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats.
        /// </summary>
        public static string Content_Seats {
            get {
                return ResourceManager.GetString("Content_Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry! Because your session is time out. Please start again..
        /// </summary>
        public static string Content_SessionTimeout {
            get {
                return ResourceManager.GetString("Content_SessionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Content_Setting {
            get {
                return ResourceManager.GetString("Content_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Content_SignIn {
            get {
                return ResourceManager.GetString("Content_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in using.
        /// </summary>
        public static string Content_SigninUsing {
            get {
                return ResourceManager.GetString("Content_SigninUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Content_SignOut {
            get {
                return ResourceManager.GetString("Content_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up using.
        /// </summary>
        public static string Content_SignupUsing {
            get {
                return ResourceManager.GetString("Content_SignupUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Content_Staff {
            get {
                return ResourceManager.GetString("Content_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffs.
        /// </summary>
        public static string Content_Staffs {
            get {
                return ResourceManager.GetString("Content_Staffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to start your session.
        /// </summary>
        public static string Content_StartSession {
            get {
                return ResourceManager.GetString("Content_StartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Content_Status {
            get {
                return ResourceManager.GetString("Content_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Content_Step {
            get {
                return ResourceManager.GetString("Content_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Payment.
        /// </summary>
        public static string Content_SubminPayment {
            get {
                return ResourceManager.GetString("Content_SubminPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Booking.
        /// </summary>
        public static string Content_SubmitBooking {
            get {
                return ResourceManager.GetString("Content_SubmitBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Order.
        /// </summary>
        public static string Content_SubmitOrder {
            get {
                return ResourceManager.GetString("Content_SubmitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTotal.
        /// </summary>
        public static string Content_SubTotal {
            get {
                return ResourceManager.GetString("Content_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Content_Success {
            get {
                return ResourceManager.GetString("Content_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Content_System {
            get {
                return ResourceManager.GetString("Content_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Content_Table {
            get {
                return ResourceManager.GetString("Content_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table in home page.
        /// </summary>
        public static string Content_TableInHome {
            get {
                return ResourceManager.GetString("Content_TableInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table list.
        /// </summary>
        public static string Content_TableList {
            get {
                return ResourceManager.GetString("Content_TableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Content_Tables {
            get {
                return ResourceManager.GetString("Content_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Type.
        /// </summary>
        public static string Content_TableType {
            get {
                return ResourceManager.GetString("Content_TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Content_Tax {
            get {
                return ResourceManager.GetString("Content_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax code.
        /// </summary>
        public static string Content_TaxCode {
            get {
                return ResourceManager.GetString("Content_TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank for your booking, check booking by email in restaurant.
        /// </summary>
        public static string Content_Thanks {
            get {
                return ResourceManager.GetString("Content_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Content_Time {
            get {
                return ResourceManager.GetString("Content_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time distance.
        /// </summary>
        public static string Content_TimeDistance {
            get {
                return ResourceManager.GetString("Content_TimeDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Content_Title {
            get {
                return ResourceManager.GetString("Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Content_To {
            get {
                return ResourceManager.GetString("Content_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Content_Today {
            get {
                return ResourceManager.GetString("Content_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Content_Total {
            get {
                return ResourceManager.GetString("Content_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Content_Type {
            get {
                return ResourceManager.GetString("Content_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string Content_Unavailable {
            get {
                return ResourceManager.GetString("Content_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompleted.
        /// </summary>
        public static string Content_Uncompleted {
            get {
                return ResourceManager.GetString("Content_Uncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Content_Unit {
            get {
                return ResourceManager.GetString("Content_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string Content_UnitContent {
            get {
                return ResourceManager.GetString("Content_UnitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Content_Update {
            get {
                return ResourceManager.GetString("Content_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Content_Username {
            get {
                return ResourceManager.GetString("Content_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string Content_ViewAll {
            get {
                return ResourceManager.GetString("Content_ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Orders .
        /// </summary>
        public static string Content_ViewOrders {
            get {
                return ResourceManager.GetString("Content_ViewOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Content_Views {
            get {
                return ResourceManager.GetString("Content_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Tables.
        /// </summary>
        public static string Content_ViewTables {
            get {
                return ResourceManager.GetString("Content_ViewTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please waiting only one!.
        /// </summary>
        public static string Content_WaitingOnlyOne {
            get {
                return ResourceManager.GetString("Content_WaitingOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web content.
        /// </summary>
        public static string Content_WebContent {
            get {
                return ResourceManager.GetString("Content_WebContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site long name.
        /// </summary>
        public static string Content_WebLongName {
            get {
                return ResourceManager.GetString("Content_WebLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site short name.
        /// </summary>
        public static string Content_WebShortName {
            get {
                return ResourceManager.GetString("Content_WebShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        public static string Massage_Error_PasswordNotMatch {
            get {
                return ResourceManager.GetString("Massage_Error_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Delete table type also delete all tables of this type!.
        /// </summary>
        public static string Message__Warning_DeleteTableType {
            get {
                return ResourceManager.GetString("Message__Warning_DeleteTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change table, cause is new table is ordered!.
        /// </summary>
        public static string Message_Error_ChangeTable {
            get {
                return ResourceManager.GetString("Message_Error_ChangeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to sever. Please check your internet!.
        /// </summary>
        public static string Message_Error_Connection {
            get {
                return ResourceManager.GetString("Message_Error_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer is ordering!.
        /// </summary>
        public static string Message_Error_Customer_Foreign {
            get {
                return ResourceManager.GetString("Message_Error_Customer_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have no data to delete!.
        /// </summary>
        public static string Message_Error_Delete {
            get {
                return ResourceManager.GetString("Message_Error_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete. Have a least of an orders in this floor!.
        /// </summary>
        public static string Message_Error_Floor_Foreign {
            get {
                return ResourceManager.GetString("Message_Error_Floor_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete. Have a least of an orders contains this food!.
        /// </summary>
        public static string Message_Error_Food_Foreign {
            get {
                return ResourceManager.GetString("Message_Error_Food_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This food is not existed!.
        /// </summary>
        public static string Message_Error_Food_Null {
            get {
                return ResourceManager.GetString("Message_Error_Food_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is not enough!.
        /// </summary>
        public static string Message_Error_Food_Quantity {
            get {
                return ResourceManager.GetString("Message_Error_Food_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not insert data. Please check and try again!.
        /// </summary>
        public static string Message_Error_Insert {
            get {
                return ResourceManager.GetString("Message_Error_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in is not successful.
        /// </summary>
        public static string Message_Error_Login {
            get {
                return ResourceManager.GetString("Message_Error_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update completed orders!.
        /// </summary>
        public static string Message_Error_Order_Completed {
            get {
                return ResourceManager.GetString("Message_Error_Order_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order is not existed.
        /// </summary>
        public static string Message_Error_Order_Null {
            get {
                return ResourceManager.GetString("Message_Error_Order_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not order Food in this case!.
        /// </summary>
        public static string Message_Error_OrderFoodGet {
            get {
                return ResourceManager.GetString("Message_Error_OrderFoodGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password do not match!.
        /// </summary>
        public static string Message_Error_PasswordConfirm {
            get {
                return ResourceManager.GetString("Message_Error_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is not existed!.
        /// </summary>
        public static string Message_Error_PermissionNoExist {
            get {
                return ResourceManager.GetString("Message_Error_PermissionNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register is not successful.
        /// </summary>
        public static string Message_Error_Register {
            get {
                return ResourceManager.GetString("Message_Error_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! System error, Please try again!.
        /// </summary>
        public static string Message_Error_System {
            get {
                return ResourceManager.GetString("Message_Error_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete. Have a least of orders in this table!.
        /// </summary>
        public static string Message_Error_Table_Foreign {
            get {
                return ResourceManager.GetString("Message_Error_Table_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete. Have a least of orders table this table type!.
        /// </summary>
        public static string Message_Error_TableType_Foreign {
            get {
                return ResourceManager.GetString("Message_Error_TableType_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not order in this case!.
        /// </summary>
        public static string Message_Error_UpdateOrder {
            get {
                return ResourceManager.GetString("Message_Error_UpdateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is existed!.
        /// </summary>
        public static string Message_Error_UserExisted {
            get {
                return ResourceManager.GetString("Message_Error_UserExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password or Username is not exist!.
        /// </summary>
        public static string Message_Error_UsernameNotExist {
            get {
                return ResourceManager.GetString("Message_Error_UsernameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is not valid. Please check and try again!.
        /// </summary>
        public static string Message_Error_Validate {
            get {
                return ResourceManager.GetString("Message_Error_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data successful!.
        /// </summary>
        public static string Message_Success_Delete {
            get {
                return ResourceManager.GetString("Message_Success_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert data successful!.
        /// </summary>
        public static string Message_Success_Insert {
            get {
                return ResourceManager.GetString("Message_Success_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in successful.
        /// </summary>
        public static string Message_Success_Login {
            get {
                return ResourceManager.GetString("Message_Success_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register successful.
        /// </summary>
        public static string Message_Success_Register {
            get {
                return ResourceManager.GetString("Message_Success_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Message success..
        /// </summary>
        public static string Message_Success_Update_Password {
            get {
                return ResourceManager.GetString("Message_Success_Update_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile success..
        /// </summary>
        public static string Message_Success_Update_Profile {
            get {
                return ResourceManager.GetString("Message_Success_Update_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email exactly..
        /// </summary>
        public static string Validate_Email {
            get {
                return ResourceManager.GetString("Validate_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {0} characters..
        /// </summary>
        public static string Validate_LenghtMax {
            get {
                return ResourceManager.GetString("Validate_LenghtMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date..
        /// </summary>
        public static string Validate_MaxDate {
            get {
                return ResourceManager.GetString("Validate_MaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value greater than or equal to {0}..
        /// </summary>
        public static string Validate_Min {
            get {
                return ResourceManager.GetString("Validate_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number only..
        /// </summary>
        public static string Validate_Number {
            get {
                return ResourceManager.GetString("Validate_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not match..
        /// </summary>
        public static string Validate_PasswordConfirm {
            get {
                return ResourceManager.GetString("Validate_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string Validate_Required {
            get {
                return ResourceManager.GetString("Validate_Required", resourceCulture);
            }
        }
    }
}
